### ISSUE TITLE
Volume plugin pulseaudio support

### ISSUE THREAD

**Issue by RichJack** [aanatoly/fbpanel#10]
Thanks so much for your quick work at resolving issues so far :)

Would it be possible to extend the volume plugin to allow for pulseaudio support?

You might be able to merge the volume plugin code from lxpanel back in which does support pulseaudio... 

A right-click option like you have for the tclock plugin could allow the user to open a mixer of their choice eg pavucontrol

Also, it would be ideal if the volume slider would disappear when you click off it rather than having to click back on the icon to close it (same for calendar/tclock plugin) - this maybe a separate issue.

Thanks!

**Comment by aanatoly** [comment]
I prefer to have such functionality to be implemented as a separate program. It runs as deamon and provides XEMBED icon for gui. 
These projects look intresting:
 * [ipha/pulse-volumeicon](https://github.com/ipha/pulse-volumeicon)
 * [Maato/volumeicon](https://github.com/Maato/volumeicon) (I use  this one)

The criteria for plugin is low dependency, here in order of preference
   * no external deps at all
   * accessing `/proc`, `/sys` only
   * acessing disk
   * launching smth very common, like `wget`
