### ISSUE TITLE
new plugin: user menu with gravatar icon

### ISSUE THREAD

**Issue by aanatoly** [aanatoly/fbpanel#11]
Requirements:
 * based on `menu` plugin
 * can use [gravatar](http://gravatar.com) image
 * can use local image
 * menu 
     * default entries:
        * logout
        * lock screen
     * default action - dialog to set a command

**Comment by RichJack** [comment]
Sound great, like the one in the Chrome OS bar? You've read my mind :)

**Comment by aanatoly** [comment]
a screenie
![2015-12-05-043518_146x92_escrotum](https://cloud.githubusercontent.com/assets/6735508/11605515/5209d240-9b0a-11e5-9b73-a45c07f7a76a.png)

**Comment by aanatoly** [comment]
Required config
```
plugin {
    type = user
    config {
        border = 2
        gravataremail = me@gmail.com
        item {
            name = Lock Display
            icon = gnome-lockscreen
            action = slock
        }
        item {
            name = logout
            icon = gnome-session-logout
            action = xlogout
        }
    }
}
```

**Comment by aanatoly** [comment]
done, see [develop](/aanatoly/fbpanel/tree/develop) branch

**Comment by RichJack** [comment]
Brilliant work again. I have set it to a static image and it works great
which is enough for me at the moment, but it didn't find my gravatar image
though using:
gravataremail = richjack@gmx.com

Is there anyway, it could find a Google+ profile image as well?

**Comment by aanatoly** [comment]
Hi
You can try  this script to fetch gravatar https://gist.github.com/aanatoly/42eac40250baaabd8643
and see where is a problem. Use `--debug` flag

It works for me with your email both in  a panel and with script

![2015-12-05-184300_219x46_escrotum](https://cloud.githubusercontent.com/assets/6735508/11608944/bd5df104-9b80-11e5-9329-d7deeaa6d787.png)

**Comment by aanatoly** [comment]
Plz post you config, I'll try to reproduce it.
Just in case, `fbpanel` stores tmp image as `/tmp/gravatar` so run the script
`./wget-gravatar --debug -e richjack@gmx.com -o /tmp/gravatar`

**Comment by RichJack** [comment]
It correctly downloads the gravatar to /tmp/gravatar but it doesn't set it on the panel. I can manually set the gravatar icon though with:
image = /tmp/gravatar

Here's my config:

```
Global {
    edge = bottom
    allign = right
    xmargin = 12
    ymargin = 5
    widthtype = request
    width = 14
    height = 35
    transparent = true
    tintcolor = #000000
    alpha = 124
    setdocktype = true
    setpartialstrut = true
    autohide = false
    heightWhenHidden = 2
    roundcorners = true
    roundcornersradius = 6
    layer = above
    MaxElemHeight = 24
    setlayer = false
}
Plugin {
    type = space
    config {
        size = 2
    }
}
Plugin {
    type = tclock
    config {
        foreground = "#ffffff"
        ClockFmt = <span font="Roboto 10" color="white"><b>%H:%M</b></span>
        TooltipFmt = %A%n%d %B %G
        ShowCalendar = true
        ShowTooltip = true
    }
}
Plugin {
    type = space
    config {
        size = 13
    }
}
Plugin {
    type = battery
}
Plugin {
    type = space
    config {
        size = 2
    }
}
Plugin {
    type = tray
}
Plugin {
    type = space
    config {
        size = 2
    }
}
plugin {
    type = user
    config {
        border = 0
        gravataremail = richjack@gmx.com
        item {
            name = Shutdown
            icon = system-shutdown-panel
            action = yad-shutdown
        }
        item {
            name = Hibernate
            icon = system-hibernate
            action = sh -c 'dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Hibernate'
        }
        item {
            name = Sleep
            icon = system-sleep
            action = sh -c 'dm-tool lock & dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend'
        }
        item {
            name = Lock Screen
            icon = gnome-lock-screen
            action = dm-tool lock
        }
        item {
            name = Switch User
            icon = switch-user
            action = dm-tool switch-to-greeter
        }
        item {
            name = Update panel
            icon = reload
            action = killall -SIGUSR1 fbpanel
        }
        item {
            name = Change Avatar
            icon = mugshot
            action = mugshot
        }
    }
}
```

**Comment by aanatoly** [comment]
What does `user` plugin do? Shows broken image, shows nothing? Can yoiu send a screenshot, plz ? It will help

**Comment by RichJack** [comment]
It comes from your code earlier in this issue when you posted the code needed to implement the gravatar plugin: https://github.com/aanatoly/fbpanel/issues/11#issuecomment-162133768

**Comment by aanatoly** [comment]
I can't reproduce it so far.
Let try this:
- kill panel
- leave in a config file only `gravataremail = richjack@gmx.com` line, 
  and remove `image = ..` and `icon = ...` lines
- remove `/tmp/gravatar`
- start panel

and send me a screenshot of what you have now. Thanks

**Comment by RichJack** [comment]
Okay, here's my stripped down config (hope it's what you meant):

```
Global {
    edge = bottom
    allign = right
    xmargin = 12
    ymargin = 5
    widthtype = request
    width = 14
    height = 35
    transparent = true
    tintcolor = #000000
    alpha = 124
    setdocktype = true
    setpartialstrut = true
    autohide = false
    heightWhenHidden = 2
    roundcorners = true
    roundcornersradius = 6
    layer = above
    MaxElemHeight = 24
    setlayer = false
}

Plugin {
    type = tclock
    config {
        foreground = "#ffffff"
        ClockFmt = <span font="Roboto 10" color="white"><b>%H:%M</b></span>
        TooltipFmt = %A%n%d %B %G
        ShowCalendar = true
        ShowTooltip = true
    }
}

plugin {
    type = user
    config {
        border = 2
        gravataremail = richjack@gmx.com
    }
}
```

Screenshot:
![fbpanel_gravatar](https://cloud.githubusercontent.com/assets/7870477/11610303/38c3185a-9b96-11e5-9f83-a20be2932cda.png)

**Comment by aanatoly** [comment]
ok, thanks.

**Comment by aanatoly** [comment]
Fixed. Now it should work, see develop branch
![2015-12-06-000201_214x62_escrotum](https://cloud.githubusercontent.com/assets/6735508/11610514/70383ef2-9bad-11e5-98c2-84def7957d84.png)

**Comment by RichJack** [comment]
Thank you, it is fixed :)

Would it be possible to allow customization of the tooltip along the lines
of:
tooltip = $USER is logged in

Also, I don't know whether you would consider allowing for a Google profile
pic as well as Gravatar? I've been looking into it and you can get it by
querying this web address with your Google username:

http://picasaweb.google.com/data/entry/api/user/${GUSERNAME}?alt=json

eg: http://picasaweb.google.com/data/entry/api/user/chromixium?alt=json

Then the website displays the full path to the logo as follows:

"gphoto$thumbnail":{"$t":"http://lh3.googleusercontent.com/-wGDIB6oPy0w/AAAAAAAAAAI/AAAAAAAAAAA/kb8-My-IGTI/s64-c/101947769087707595037.jpg"}}}

There's more info here:
http://stackoverflow.com/questions/9128700/getting-google-profile-picture-url-with-user-id

Kind regards
RichJack

**Comment by RichJack** [comment]
Actually, if you decide to implement this, could the icon be downloaded to
~/.face ?

That way it would be set as the login avatar in lightdm...

Don't worry if you don't want to implement this, as I can script it to
create the .face file and run at startup and then just set the image =
parameter in the plugin. It'd just be cool that's all!

**Comment by aanatoly** [comment]
Feature request are welcome. big and small
I suggest to open an issue for each one of them, as we did before.
