### ISSUE TITLE
Nothing appears after battery plugin

### ISSUE THREAD

**Issue by RichJack** [aanatoly/fbpanel#13]
On devel branch...

Whatever is set after the battery plugin in the config isn't shown on the panel. So if I put the systray after the battery plugin, the systray doesn't appear.

**Comment by aanatoly** [comment]
plz try `menu` plugin it must be visible all the time, while `systray` may hide itself if there is another tray already

**Comment by aanatoly** [comment]
Please post your config

**Comment by RichJack** [comment]
Sorry aanatoly, it seems to be working at present with the latest devel branch. I swear it wouldn't work yesterday, but just now it is okay. I'll close this.
