### ISSUE TITLE
Include option for vertical (y) and horizontal (x) margin

### ISSUE THREAD

**Issue by RichJack** [aanatoly/fbpanel#2]
As discussed by email, thanks :)

I would like to try to recreate the floating tray area from Chrome OS:
http://www.omgchrome.com/wp-content/uploads/2013/07/chromeos-status-bar.jpg 

You have made allowances for a margin, but this only allows me to move the panel in from the left. What I would like to be able to do, is move the panel up from the bottom by about 5-10 pixels.

I guess what would be ideal is an x margin and a y margin feature that moves the panel in the required number of pixels from the screen edge it is attached to. What I don't want is an absolute position feature, as it needs to be able to stay in place even when changing screen resolution.

Eg The panel is aligned bottom/right. The X margin would move the panel to the left, away from the right-edge (the existing margin feature) and the Y margin would move the panel up from the bottom edge.

Hope this makes sense! Thanks for getting the project back up and running!

**Comment by aanatoly** [comment]
It's ready, see `develop` branch

**Comment by RichJack** [comment]
OMG that was quick, and it works brilliantly, thank you! I can't tell you
how much I have wanted such a simple thing in a dock/panel!

I hope you don't mind if I open another issue re: rounded corners..?
